'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace PX_Facturacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ssingest.cl/TO/WS", ConfigurationName:="PX_Facturacion.FacturacionSoap")>  _
    Public Interface FacturacionSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ObtenerDato", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerDato(ByVal iTx As String) As PX_Facturacion.ListaDataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ListarParametro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarParametro(ByVal where As String) As PX_Facturacion.ListaDataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/GuardarCambioParametros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GuardarCambioParametros(ByVal agencia As String, ByVal usuario As String, ByVal timer As Integer, ByVal facturacionAutomatica As Integer, ByVal motivo As String, ByVal terminal As String) As PX_Facturacion.Parametro
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ListarDespachoCamion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarDespachoCamion(ByVal agencia As String) As PX_Facturacion.ListaDataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/GuardarLogViaje", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GuardarLogViaje(ByVal viaje As String, ByVal agencia As String, ByVal usuario As String, ByVal estadoGuiaDespacho As String, ByVal fechaGuiaDespacho As String, ByVal respuestaGuiaDespacho As String, ByVal nroINET As Integer, ByVal estadoFacturacion As String, ByVal fechaFacturacion As String, ByVal respuestaFacturacion As String, ByVal terminal As String) As PX_Facturacion.Viaje
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ObtenerInformacionViaje", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerInformacionViaje(ByVal viaje As String, ByVal origen As String) As PX_Facturacion.Viaje
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ValidaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidaCliente(ByVal iPor As Long, ByVal iClte As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/PersitirDatosEvento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PersitirDatosEvento(ByVal iEvento As String, ByVal iObs As String, ByVal iClte As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ObtenerTotalDespachoSiguienteSemana_V2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerTotalDespachoSiguienteSemana_V2(ByVal iRut As String, ByVal iTipo As String, ByVal NroDias As Integer) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerDatosLN_Cliente(ByVal iRut As String) As PX_Facturacion.ListaDataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente_V2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerDatosLN_Cliente_V2(ByVal iRut As String, ByVal iNroDias As Integer) As PX_Facturacion.ListaDataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/NotificarEvento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function NotificarEvento(ByVal iEvento As String, ByVal iClte As String, ByVal iPorcentaje As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/CambiaEstadoCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CambiaEstadoCliente(ByVal iRut As String, ByVal lEstado As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/EnviaCorreoNotificacion_LC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EnviaCorreoNotificacion_LC(ByVal iRut As String, ByVal iTipoNot As String, ByVal iListDest As String, ByVal iRZ As String, ByVal iTLC As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.ssingest.cl/TO/WS/Obtener_LINEA_CREDITO", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Obtener_LINEA_CREDITO() As System.Data.DataSet
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ssingest.cl/TO/WS")>  _
    Partial Public Class ListaDataSet
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private _dataSetField As System.Data.DataSet
        
        Private _errorField As String
        
        Private dataSetField As System.Data.DataSet
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property _dataSet() As System.Data.DataSet
            Get
                Return Me._dataSetField
            End Get
            Set
                Me._dataSetField = value
                Me.RaisePropertyChanged("_dataSet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property _error() As String
            Get
                Return Me._errorField
            End Get
            Set
                Me._errorField = value
                Me.RaisePropertyChanged("_error")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property DataSet() As System.Data.DataSet
            Get
                Return Me.dataSetField
            End Get
            Set
                Me.dataSetField = value
                Me.RaisePropertyChanged("DataSet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ssingest.cl/TO/WS")>  _
    Partial Public Class Viaje
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private viaje1Field As String
        
        Private estadoGuiaField As String
        
        Private fechaGuiaField As String
        
        Private nroINETField As Short
        
        Private estadoFacturaField As String
        
        Private fechaFacturaField As String
        
        Private respuestaGuiaField As String
        
        Private respuestaFacturaField As String
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Viaje", Order:=0)>  _
        Public Property Viaje1() As String
            Get
                Return Me.viaje1Field
            End Get
            Set
                Me.viaje1Field = value
                Me.RaisePropertyChanged("Viaje1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property EstadoGuia() As String
            Get
                Return Me.estadoGuiaField
            End Get
            Set
                Me.estadoGuiaField = value
                Me.RaisePropertyChanged("EstadoGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property FechaGuia() As String
            Get
                Return Me.fechaGuiaField
            End Get
            Set
                Me.fechaGuiaField = value
                Me.RaisePropertyChanged("FechaGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NroINET() As Short
            Get
                Return Me.nroINETField
            End Get
            Set
                Me.nroINETField = value
                Me.RaisePropertyChanged("NroINET")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property EstadoFactura() As String
            Get
                Return Me.estadoFacturaField
            End Get
            Set
                Me.estadoFacturaField = value
                Me.RaisePropertyChanged("EstadoFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaFactura() As String
            Get
                Return Me.fechaFacturaField
            End Get
            Set
                Me.fechaFacturaField = value
                Me.RaisePropertyChanged("FechaFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property RespuestaGuia() As String
            Get
                Return Me.respuestaGuiaField
            End Get
            Set
                Me.respuestaGuiaField = value
                Me.RaisePropertyChanged("RespuestaGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property RespuestaFactura() As String
            Get
                Return Me.respuestaFacturaField
            End Get
            Set
                Me.respuestaFacturaField = value
                Me.RaisePropertyChanged("RespuestaFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ssingest.cl/TO/WS")>  _
    Partial Public Class Parametro
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tablaField As String
        
        Private codIntField As String
        
        Private descripcionField As String
        
        Private alf1Field As String
        
        Private alf2Field As String
        
        Private alf3Field As String
        
        Private num1Field As Integer
        
        Private num2Field As Integer
        
        Private num3Field As Integer
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Tabla() As String
            Get
                Return Me.tablaField
            End Get
            Set
                Me.tablaField = value
                Me.RaisePropertyChanged("Tabla")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodInt() As String
            Get
                Return Me.codIntField
            End Get
            Set
                Me.codIntField = value
                Me.RaisePropertyChanged("CodInt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Alf1() As String
            Get
                Return Me.alf1Field
            End Get
            Set
                Me.alf1Field = value
                Me.RaisePropertyChanged("Alf1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Alf2() As String
            Get
                Return Me.alf2Field
            End Get
            Set
                Me.alf2Field = value
                Me.RaisePropertyChanged("Alf2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Alf3() As String
            Get
                Return Me.alf3Field
            End Get
            Set
                Me.alf3Field = value
                Me.RaisePropertyChanged("Alf3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Num1() As Integer
            Get
                Return Me.num1Field
            End Get
            Set
                Me.num1Field = value
                Me.RaisePropertyChanged("Num1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Num2() As Integer
            Get
                Return Me.num2Field
            End Get
            Set
                Me.num2Field = value
                Me.RaisePropertyChanged("Num2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Num3() As Integer
            Get
                Return Me.num3Field
            End Get
            Set
                Me.num3Field = value
                Me.RaisePropertyChanged("Num3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FacturacionSoapChannel
        Inherits PX_Facturacion.FacturacionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FacturacionSoapClient
        Inherits System.ServiceModel.ClientBase(Of PX_Facturacion.FacturacionSoap)
        Implements PX_Facturacion.FacturacionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerDato(ByVal iTx As String) As PX_Facturacion.ListaDataSet Implements PX_Facturacion.FacturacionSoap.ObtenerDato
            Return MyBase.Channel.ObtenerDato(iTx)
        End Function
        
        Public Function ListarParametro(ByVal where As String) As PX_Facturacion.ListaDataSet Implements PX_Facturacion.FacturacionSoap.ListarParametro
            Return MyBase.Channel.ListarParametro(where)
        End Function
        
        Public Function GuardarCambioParametros(ByVal agencia As String, ByVal usuario As String, ByVal timer As Integer, ByVal facturacionAutomatica As Integer, ByVal motivo As String, ByVal terminal As String) As PX_Facturacion.Parametro Implements PX_Facturacion.FacturacionSoap.GuardarCambioParametros
            Return MyBase.Channel.GuardarCambioParametros(agencia, usuario, timer, facturacionAutomatica, motivo, terminal)
        End Function
        
        Public Function ListarDespachoCamion(ByVal agencia As String) As PX_Facturacion.ListaDataSet Implements PX_Facturacion.FacturacionSoap.ListarDespachoCamion
            Return MyBase.Channel.ListarDespachoCamion(agencia)
        End Function
        
        Public Function GuardarLogViaje(ByVal viaje As String, ByVal agencia As String, ByVal usuario As String, ByVal estadoGuiaDespacho As String, ByVal fechaGuiaDespacho As String, ByVal respuestaGuiaDespacho As String, ByVal nroINET As Integer, ByVal estadoFacturacion As String, ByVal fechaFacturacion As String, ByVal respuestaFacturacion As String, ByVal terminal As String) As PX_Facturacion.Viaje Implements PX_Facturacion.FacturacionSoap.GuardarLogViaje
            Return MyBase.Channel.GuardarLogViaje(viaje, agencia, usuario, estadoGuiaDespacho, fechaGuiaDespacho, respuestaGuiaDespacho, nroINET, estadoFacturacion, fechaFacturacion, respuestaFacturacion, terminal)
        End Function
        
        Public Function ObtenerInformacionViaje(ByVal viaje As String, ByVal origen As String) As PX_Facturacion.Viaje Implements PX_Facturacion.FacturacionSoap.ObtenerInformacionViaje
            Return MyBase.Channel.ObtenerInformacionViaje(viaje, origen)
        End Function
        
        Public Function ValidaCliente(ByVal iPor As Long, ByVal iClte As String) As Boolean Implements PX_Facturacion.FacturacionSoap.ValidaCliente
            Return MyBase.Channel.ValidaCliente(iPor, iClte)
        End Function
        
        Public Function PersitirDatosEvento(ByVal iEvento As String, ByVal iObs As String, ByVal iClte As String) As String Implements PX_Facturacion.FacturacionSoap.PersitirDatosEvento
            Return MyBase.Channel.PersitirDatosEvento(iEvento, iObs, iClte)
        End Function
        
        Public Function ObtenerTotalDespachoSiguienteSemana_V2(ByVal iRut As String, ByVal iTipo As String, ByVal NroDias As Integer) As Long Implements PX_Facturacion.FacturacionSoap.ObtenerTotalDespachoSiguienteSemana_V2
            Return MyBase.Channel.ObtenerTotalDespachoSiguienteSemana_V2(iRut, iTipo, NroDias)
        End Function
        
        Public Function ObtenerDatosLN_Cliente(ByVal iRut As String) As PX_Facturacion.ListaDataSet Implements PX_Facturacion.FacturacionSoap.ObtenerDatosLN_Cliente
            Return MyBase.Channel.ObtenerDatosLN_Cliente(iRut)
        End Function
        
        Public Function ObtenerDatosLN_Cliente_V2(ByVal iRut As String, ByVal iNroDias As Integer) As PX_Facturacion.ListaDataSet Implements PX_Facturacion.FacturacionSoap.ObtenerDatosLN_Cliente_V2
            Return MyBase.Channel.ObtenerDatosLN_Cliente_V2(iRut, iNroDias)
        End Function
        
        Public Function NotificarEvento(ByVal iEvento As String, ByVal iClte As String, ByVal iPorcentaje As Long) As Boolean Implements PX_Facturacion.FacturacionSoap.NotificarEvento
            Return MyBase.Channel.NotificarEvento(iEvento, iClte, iPorcentaje)
        End Function
        
        Public Function CambiaEstadoCliente(ByVal iRut As String, ByVal lEstado As Boolean) As String Implements PX_Facturacion.FacturacionSoap.CambiaEstadoCliente
            Return MyBase.Channel.CambiaEstadoCliente(iRut, lEstado)
        End Function
        
        Public Function EnviaCorreoNotificacion_LC(ByVal iRut As String, ByVal iTipoNot As String, ByVal iListDest As String, ByVal iRZ As String, ByVal iTLC As String) As String Implements PX_Facturacion.FacturacionSoap.EnviaCorreoNotificacion_LC
            Return MyBase.Channel.EnviaCorreoNotificacion_LC(iRut, iTipoNot, iListDest, iRZ, iTLC)
        End Function
        
        Public Function Obtener_LINEA_CREDITO() As System.Data.DataSet Implements PX_Facturacion.FacturacionSoap.Obtener_LINEA_CREDITO
            Return MyBase.Channel.Obtener_LINEA_CREDITO
        End Function
    End Class
End Namespace
